### Implementing AND Gate using Neural Network

#### WhiteBox Implementation

In [1]:
# Importing the libraries
import numpy as np
import random
import math

In [2]:
alpha = 0.5 # Learning Rate

In [3]:
# Input array 
arr = [[0,0],[0,1],[1,0]] #Inputs for an OR Gate
#Converting the list to a numpy array
inp = np.array(arr)
inp

array([[0, 0],
       [0, 1],
       [1, 0]])

In [4]:
#Output array
arr1 = [[0,0],[0,0],[0,0]] #Taking 1 as [1,1] and 0 as [0,0]
#Converting the output list to a numpy array
opt = np.array(arr1)
opt

array([[0, 0],
       [0, 0],
       [0, 0]])

In [5]:
#Assigning weights randomly
weights = []
for i in range(6): 
    weights.append(random.randrange(1,10))
lw1 = weights[:2]
lw2 = weights[2:4]
lw3 = weights[4:6]
wt = np.array([lw1,lw2,lw3]) #Converting the weights to a numpy array
wt

array([[8, 4],
       [9, 1],
       [8, 8]])

#### Forward Propagation


##### Multiplier Function


In [6]:
def multiplier(weights,sigarray):  #Multiplying the inputs/sigmoid array with weights
    mul = weights*sigarray
    return mul

##### Sigmoid Function

In [7]:
def sigmoid(x):
    z = 1/(1 + np.exp(-x))
    return z

In [8]:
vector = np.vectorize(sigmoid) # Takes a sequence numpy arrays as input and returns a single numpy array
# It evaluates the function(sigmoid) over successive input arrays

In [9]:
for i in range(0,len(inp)):
    layer1 = vector(multiplier(wt[0],inp[i])) #Values for layer1 (Input layer)
    layer2 = vector(multiplier(wt[1],layer1)) #Values for layer2 (Hidden layer)
    layer3 = vector(multiplier(wt[2],layer2)) #Values for layer3 (Output layer)
    
    #Backward Propagation
    
    er3 = (opt[i] - layer3)*(np.ones(2) - layer3)*layer3*layer2 #Differentitation of performance wrt weight3
    wt[2] = wt[2] + (alpha * er3) #Optimization of weight3
    er2 = (opt[i] - layer3)*(np.ones(2) - layer3)* layer3 * wt[2] * (np.ones(2) - layer2) * layer2 * layer1 #Differentitation of performance wrt weight2
    wt[1] = wt[1] + (alpha * er2) #Optimization of weight2
    er1 = (opt[i] - layer3)*(np.ones(2) - layer3)*layer3*wt[2]*(np.ones(2) - layer2)*layer2*wt[1]*(np.ones(2) - layer1)*layer1*inp[i] #Differentitation of performance wrt weight1
    wt[0] = wt[0] + (alpha * er1) #Optimization of weight1

In [10]:
print(wt) #Indicates that the weights are optimized

[[7 4]
 [6 0]
 [5 5]]


#### Test Case

In [11]:
sample = np.array([1,1]) #Input of test case

In [12]:
sample

array([1, 1])

In [13]:
layer1 = vector(multiplier(wt[0],sample))
layer2 = vector(multiplier(wt[1],sample)) 
layer3 = vector(multiplier(wt[2],sample)) 

In [14]:
layer3 #Output of the test case

array([0.99330715, 0.99330715])

#### BlackBox Implementation

In [17]:
#Importing the necessary libraries
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [18]:
# Input arrays
a = np.array([0, 0, 1, 1])
b = np.array([0, 1, 0, 1])
# Output array
opt = np.array([0, 0, 0, 1])

In [19]:
# Final input array is obtained after combining the input elements into a new array.
total_input = []

for i, j in zip(a, b):
    input1 = []
    input1.append(i)
    input1.append(j)
    total_input.append(input1)
    
total_input = np.array(total_input) #Final input array
total_input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [22]:
# Create lists to store the training data for both input and output
x_train = []
y_train = []

for i, j in zip(total_input, opt):
    x_train.append(i)
    y_train.append(j)
    
x_train = np.array(x_train)
y_train = np.array(y_train)

In [23]:

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

# Construct a Sequential type model to solve the required OR Gate task
# The final output layer contains the Sigmoid activation function
model = Sequential()
model.add(Input(shape = x_train[0].shape))
model.add(Dense(10, activation = "relu"))
model.add(Dense(10, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))
# Shows the summary of the Sequential type network containing the hidden layers and output node with their respective parameters
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [24]:
# To compile the model and train it
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = "binary_accuracy")

In [25]:
model.fit(x_train, y_train, epochs = 500)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 0.6880 - binary_accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6862 - binary_accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6844 - binary_accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6825 - binary_accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6807 - binary_accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6789 - binary_accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6771 - binary_accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6755 - binary_accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6740 - binary_accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 11m

1/1 [==============================] - 0s 8ms/step - loss: 0.5951 - binary_accuracy: 0.7500
Epoch 79/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5942 - binary_accuracy: 0.7500
Epoch 80/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5933 - binary_accuracy: 0.7500
Epoch 81/500
1/1 [==============================] - 0s 10ms/step - loss: 0.5923 - binary_accuracy: 0.7500
Epoch 82/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5913 - binary_accuracy: 0.7500
Epoch 83/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5902 - binary_accuracy: 0.7500
Epoch 84/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5891 - binary_accuracy: 0.7500
Epoch 85/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5879 - binary_accuracy: 0.7500
Epoch 86/500
1/1 [==============================] - 0s 9ms/step - loss: 0.5869 - binary_accuracy: 0.7500
Epoch 87/500
1/1 [==============================] - 0s 7ms/step - l

1/1 [==============================] - 0s 12ms/step - loss: 0.5024 - binary_accuracy: 1.0000
Epoch 156/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5010 - binary_accuracy: 1.0000
Epoch 157/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4996 - binary_accuracy: 1.0000
Epoch 158/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4983 - binary_accuracy: 1.0000
Epoch 159/500
1/1 [==============================] - 0s 10ms/step - loss: 0.4969 - binary_accuracy: 1.0000
Epoch 160/500
1/1 [==============================] - 0s 9ms/step - loss: 0.4954 - binary_accuracy: 1.0000
Epoch 161/500
1/1 [==============================] - 0s 16ms/step - loss: 0.4941 - binary_accuracy: 1.0000
Epoch 162/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4927 - binary_accuracy: 1.0000
Epoch 163/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4912 - binary_accuracy: 1.0000
Epoch 164/500
1/1 [==============================] - 0s 6

1/1 [==============================] - 0s 12ms/step - loss: 0.3757 - binary_accuracy: 1.0000
Epoch 233/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3741 - binary_accuracy: 1.0000
Epoch 234/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3726 - binary_accuracy: 1.0000
Epoch 235/500
1/1 [==============================] - 0s 11ms/step - loss: 0.3710 - binary_accuracy: 1.0000
Epoch 236/500
1/1 [==============================] - 0s 14ms/step - loss: 0.3694 - binary_accuracy: 1.0000
Epoch 237/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3678 - binary_accuracy: 1.0000
Epoch 238/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3662 - binary_accuracy: 1.0000
Epoch 239/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3645 - binary_accuracy: 1.0000
Epoch 240/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3628 - binary_accuracy: 1.0000
Epoch 241/500
1/1 [==============================] - 0s

1/1 [==============================] - 0s 15ms/step - loss: 0.2534 - binary_accuracy: 1.0000
Epoch 310/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2520 - binary_accuracy: 1.0000
Epoch 311/500
1/1 [==============================] - 0s 9ms/step - loss: 0.2505 - binary_accuracy: 1.0000
Epoch 312/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2490 - binary_accuracy: 1.0000
Epoch 313/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2475 - binary_accuracy: 1.0000
Epoch 314/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2460 - binary_accuracy: 1.0000
Epoch 315/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2445 - binary_accuracy: 1.0000
Epoch 316/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2431 - binary_accuracy: 1.0000
Epoch 317/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2416 - binary_accuracy: 1.0000
Epoch 318/500
1/1 [==============================] - 0s 9

1/1 [==============================] - 0s 15ms/step - loss: 0.1550 - binary_accuracy: 1.0000
Epoch 387/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1539 - binary_accuracy: 1.0000
Epoch 388/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1529 - binary_accuracy: 1.0000
Epoch 389/500
1/1 [==============================] - 0s 14ms/step - loss: 0.1519 - binary_accuracy: 1.0000
Epoch 390/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1509 - binary_accuracy: 1.0000
Epoch 391/500
1/1 [==============================] - 0s 14ms/step - loss: 0.1499 - binary_accuracy: 1.0000
Epoch 392/500
1/1 [==============================] - 0s 15ms/step - loss: 0.1488 - binary_accuracy: 1.0000
Epoch 393/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1479 - binary_accuracy: 1.0000
Epoch 394/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1469 - binary_accuracy: 1.0000
Epoch 395/500
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 8ms/step - loss: 0.0945 - binary_accuracy: 1.0000
Epoch 464/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0939 - binary_accuracy: 1.0000
Epoch 465/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0933 - binary_accuracy: 1.0000
Epoch 466/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0927 - binary_accuracy: 1.0000
Epoch 467/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0922 - binary_accuracy: 1.0000
Epoch 468/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0916 - binary_accuracy: 1.0000
Epoch 469/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0910 - binary_accuracy: 1.0000
Epoch 470/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0905 - binary_accuracy: 1.0000
Epoch 471/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0900 - binary_accuracy: 1.0000
Epoch 472/500
1/1 [==============================] - 0s

In [27]:
# Perform the prediction on the dataset
model.predict(x_train)

1/1 [==============================] - 0s 41ms/step


array([[0.04344702],
       [0.03601768],
       [0.10553207],
       [0.89684916]], dtype=float32)