### Implementing OR Gate using Neural Network

#### WhiteBox Implementation

In [67]:
# Importing the libraries
import numpy as np
import random
import math

In [68]:
alpha = 0.5 # Learning Rate

In [69]:
# Input array 
arr = [[0,0],[0,1],[1,0]] #Inputs for an OR Gate
#Converting the list to a numpy array
inp = np.array(arr)
inp

array([[0, 0],
       [0, 1],
       [1, 0]])

In [70]:
#Output array
arr1 = [[0,0],[1,1],[1,1]]
#Converting the output list to a numpy array
opt = np.array(arr1)
opt

array([[0, 0],
       [1, 1],
       [1, 1]])

In [71]:
#Assigning weights randomly
weights = []
for i in range(6): 
    weights.append(random.randrange(1,10))
lw1 = weights[:2]
lw2 = weights[2:4]
lw3 = weights[4:6]
wt = np.array([lw1,lw2,lw3]) #Converting the weights to a numpy array
wt

array([[7, 1],
       [8, 4],
       [5, 7]])

#### Forward Propagation


##### Multiplier Function


In [72]:
def multiplier(weights,sigarray):  #Multiplying the inputs/sigmoid array with weights
    mul = weights*sigarray
    return mul

##### Sigmoid Function

In [73]:
def sigmoid(x):
    z = 1/(1 + np.exp(-x))
    return z

In [74]:
vector = np.vectorize(sigmoid) # Takes a sequence numpy arrays as input and returns a single numpy array
# It evaluates the function(sigmoid) over successive input arrays

In [75]:
for i in range(0,len(inp)):
    layer1 = vector(multiplier(wt[0],inp[i])) #Values for layer1 (Input layer)
    layer2 = vector(multiplier(wt[1],layer1)) #Values for layer2 (Hidden layer)
    layer3 = vector(multiplier(wt[2],layer2)) #Values for layer3 (Output layer)
    
    #Backward Propagation
    
    er3 = (opt[i] - layer3)*(np.ones(2) - layer3)*layer3*layer2 #Differentitation of performance wrt weight3
    wt[2] = wt[2] + (alpha * er3) #Optimization of weight3
    er2 = (opt[i] - layer3)*(np.ones(2) - layer3)* layer3 * wt[2] * (np.ones(2) - layer2) * layer2 * layer1 #Differentitation of performance wrt weight2
    wt[1] = wt[1] + (alpha * er2) #Optimization of weight2
    er1 = (opt[i] - layer3)*(np.ones(2) - layer3)*layer3*wt[2]*(np.ones(2) - layer2)*layer2*wt[1]*(np.ones(2) - layer1)*layer1*inp[i] #Differentitation of performance wrt weight1
    wt[0] = wt[0] + (alpha * er1) #Optimization of weight1

In [76]:
print(wt) #Indicates that the weights are optimized

[[7 1]
 [7 3]
 [4 6]]


#### Test Case

In [77]:
sample = np.array([1,1]) #Input of test case

In [78]:
sample

array([1, 1])

In [79]:
layer1 = vector(multiplier(wt[0],sample))
layer2 = vector(multiplier(wt[1],sample)) 
layer3 = vector(multiplier(wt[2],sample)) 

In [80]:
layer3 #Output of the test case

array([0.98201379, 0.99752738])

#### BlackBox Implementation

In [92]:
#Importing the necessary libraries
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [93]:
# Input arrays
a = np.array([0, 0, 1, 1])
b = np.array([0, 1, 0, 1])
# Output array
opt = np.array([0, 1, 1, 1])

In [95]:
# Final input array is obtained after combining the input elements into a new array.
total_input = []

for i, j in zip(a, b):
    input1 = []
    input1.append(i)
    input1.append(j)
    total_input.append(input1)
    
total_input = np.array(total_input) #Final input array
total_input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [86]:
# Create lists to store the training data for both input and output
x_train = []
y_train = []

for i, j in zip(total_input, y_and):
    x_train.append(i)
    y_train.append(j)
    
x_train = np.array(x_train)
y_train = np.array(y_train)

In [87]:

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

# Construct a Sequential type model to solve the required OR Gate task
# The final output layer contains the Sigmoid activation function
model = Sequential()
model.add(Input(shape = x_train[0].shape))
model.add(Dense(10, activation = "relu"))
model.add(Dense(10, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))
# Shows the summary of the Sequential type network containing the hidden layers and output node with their respective parameters
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [88]:
# To compile the model and train it
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = "binary_accuracy")

In [89]:
model.fit(x_train, y_train, epochs = 500)

Epoch 1/500
1/1 [==============================] - 1s 538ms/step - loss: 0.6255 - binary_accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6225 - binary_accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6196 - binary_accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 521us/step - loss: 0.6167 - binary_accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6139 - binary_accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6110 - binary_accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 0s/step - loss: 0.6082 - binary_accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6053 - binary_accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6025 - binary_accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 8ms/

1/1 [==============================] - 0s 7ms/step - loss: 0.4454 - binary_accuracy: 0.7500
Epoch 80/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4438 - binary_accuracy: 0.7500
Epoch 81/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4422 - binary_accuracy: 0.7500
Epoch 82/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4406 - binary_accuracy: 0.7500
Epoch 83/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4390 - binary_accuracy: 0.7500
Epoch 84/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4375 - binary_accuracy: 0.7500
Epoch 85/500
1/1 [==============================] - 0s 13ms/step - loss: 0.4359 - binary_accuracy: 0.7500
Epoch 86/500
1/1 [==============================] - 0s 14ms/step - loss: 0.4344 - binary_accuracy: 0.7500
Epoch 87/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4329 - binary_accuracy: 0.7500
Epoch 88/500
1/1 [==============================] - 0s 0s/step - l

1/1 [==============================] - 0s 0s/step - loss: 0.2839 - binary_accuracy: 0.7500
Epoch 234/500
1/1 [==============================] - 0s 0s/step - loss: 0.2830 - binary_accuracy: 0.7500
Epoch 235/500
1/1 [==============================] - 0s 9ms/step - loss: 0.2820 - binary_accuracy: 0.7500
Epoch 236/500
1/1 [==============================] - 0s 0s/step - loss: 0.2811 - binary_accuracy: 0.7500
Epoch 237/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2801 - binary_accuracy: 0.7500
Epoch 238/500
1/1 [==============================] - 0s 0s/step - loss: 0.2791 - binary_accuracy: 0.7500
Epoch 239/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2781 - binary_accuracy: 0.7500
Epoch 240/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2772 - binary_accuracy: 0.7500
Epoch 241/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2762 - binary_accuracy: 0.7500
Epoch 242/500
1/1 [==============================] - 0s 0s/step 

1/1 [==============================] - 0s 0s/step - loss: 0.1884 - binary_accuracy: 1.0000
Epoch 388/500
1/1 [==============================] - 0s 0s/step - loss: 0.1881 - binary_accuracy: 1.0000
Epoch 389/500
1/1 [==============================] - 0s 0s/step - loss: 0.1877 - binary_accuracy: 1.0000
Epoch 390/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1874 - binary_accuracy: 1.0000
Epoch 391/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1871 - binary_accuracy: 1.0000
Epoch 392/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1868 - binary_accuracy: 1.0000
Epoch 393/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1864 - binary_accuracy: 1.0000
Epoch 394/500
1/1 [==============================] - 0s 0s/step - loss: 0.1861 - binary_accuracy: 1.0000
Epoch 395/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1858 - binary_accuracy: 1.0000
Epoch 396/500
1/1 [==============================] - 0s 8ms/step

In [90]:
# Perform the prediction on the dataset
model.predict(x_train)

1/1 [==============================] - 0s 122ms/step


array([[0.44345444],
       [0.9650751 ],
       [0.98430836],
       [0.99917805]], dtype=float32)